webcams:
    -
        name: 'cam_01'
        port: '/dev/video0'
    -
        name: 'cam_02'
        port: '/dev/video1'
directories:
    images: '/var/panoptes/images'
    webcam: '/var/panoptes/webcams'
    data: '/var/panoptes/data'
environment:
    auto_detect: True
weather:
    station: mongo
    web_service:
      name: 'aat-metdata'
      link: 'http://site.aao.gov.au/met/metdata.dat'
      column_names:  ['Time (UTC)',
                      'Outside air temperature',
                      'Dome air temperature',
                      'Mirror temperature',
                      'Dome dewpoint',
                      'Outside humidity',
                      'Barometric pressure',
                      'Average wind speed',
                      'Maximum wind gust',
                      'Average wind direction',
                      'Dome door status', # closed = 0 | partially open = 2 | open = 4
                      'Rain sensor', # no rain = 0 | rain > 0
                      'Outside dewpoint',
                      'Sky-ambient',
                      'Sky-ambient uncertainty',
                      'Boltwood sky brightness', # dark = 0 | light > 0
                      'Boltwood rain flag', # no rain = 0 | rain > 0
                      'Boltwood wet flag', # dry = 0 | wet > 0
                      'Rain since 9am',
                      'SQM sky brightness']
      # be sure to have the same number of entries in column_names and column_units
      column_units:  [u.dimensionless_unscaled,
                      u.Celsius,
                      u.Celsius,
                      u.Celsius,
                      u.Celsius,
                      u.percent,
                      cds.mmHg,
                      u.km / u.hour,
                      u.km / u.hour,
                      u.degree,
                      u.dimensionless_unscaled,
                      u.dimensionless_unscaled,
                      u.Celsius,
                      u.Celsius,
                      u.Celsius,
                      u.dimensionless_unscaled,
                      u.dimensionless_unscaled,
                      u.dimensionless_unscaled,
                      u.mm,
                      u.ABmag]
      max_age: 60.
      cache_age: 1.382e10
      sky_ambient: 'Sky-ambient'
      sky_ambient_uncertainty: 'Sky-ambient uncertainty'
      average_wind_speed: 'Average wind speed'
      maximum_wind_gust: 'Maximum wind gust'
      rain_sensor: 'Rain sensor'
      rain_flag: 'Boltwood rain flag'
      wet_flag: 'Boltwood wet flag'
      threshold_rain: 0
      threshold_wet: 0
    aag_cloud:
        name: 'aag-cloudsensor'
        serial_port: '/dev/ttyUSB1'
        threshold_cloudy: -25
        threshold_very_cloudy: -15.
        threshold_windy: 50.
        threshold_very_windy: 75.
        threshold_gusty: 100.
        threshold_very_gusty: 125.
        threshold_wet: 2200.
        threshold_rainy: 1800.
        safety_delay: 15 ## minutes
        heater:
            low_temp: 0 ## deg C
            low_delta: 6 ## deg C
            high_temp: 20 ## deg C
            high_delta: 4 ## deg C
            min_power: 10 ## percent
            impulse_temp: 10 ## deg C
            impulse_duration: 60 ## seconds
            impulse_cycle: 600 ## seconds
    plot:
        amb_temp_limits: [-5, 35]
        cloudiness_limits: [-45, 5]
        wind_limits: [0, 75]
        rain_limits: [700, 3200]
        pwm_limits: [-5, 105]
